### PR TITLE
Add firefox history module to memacs

### PR DESCRIPTION
**Pull request by kidd**
Hi, I created this module to create an org file from your whole history on firefox history db.

Looks like it's working fine, but as I asked in #48 , it's quite impractical in my box due to the big data file that gets generated (20+ Megs).

### CODE REVIEW

**Comment by alphapapa** [comment]
I can only imagine how enormous this Org file would be with my Firefox profile.  :rofl:

**Comment by kidd** [comment]
Mine is just from last 6 months.... so yep, it can grow huge

**Comment by novoid** [comment]
Would you please add a documentation file as well? Take a look at https://github.com/novoid/Memacs/tree/master/docs - it is written quite fast, when you know the module ;-)

Thanks!

**Comment by kidd** [comment]
hey!

I updated some docs. Very simple, but I hope it's enough (the module is very simple also)

**Comment by novoid** [comment]
Hi @kidd,

Thanks very much for this module!

I personally was using http://shelve.sourceforge.net/ the longest time which not only indexes my web page history (via timestamps of filenames) but also the content. However, for various reasons I stopped using it. With your module, I can start logging my browser history again - thank you very much!

**Comment by novoid** [comment]
I also added a `--omit-drawer` option to get smaller output files when info within drawer is not necessary.

TODO: somebody might volunteer for coding the append mode, where output is written to a file (instead of stdout) and new entries are compared with existing ones. Only non existing entries are appended. This is helpful when Firefox SQLite DB is a sliding window and memacs output file should cover the whole story. See #51

**Pull request merged**
